#add this file to your meteor package as `.travis.yml`

sudo: required
language: node_js
node_js:
  - "0.10"

before_install:
  - "curl -L https://git.io/ejPSng | /bin/sh"
  - "npm install -g mocha"

install:
  - "npm install chai"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
script:
  -meteor test --once --driver-package dispatch:mocha
